/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel Obiajuru
 */
public class addEmployee extends javax.swing.JFrame {
Connection conn =null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form addEmployee
     */
    public addEmployee() {
        initComponents();
        conn =db.java_db();
         Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        txt_dept = new javax.swing.JTextField();
        txt_job = new javax.swing.JTextField();
        txt_doh = new javax.swing.JTextField();
        txt_salary = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        txt_apt = new javax.swing.JTextField();
        txt_pc = new javax.swing.JTextField();
        txt_design = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        txt_address2 = new javax.swing.JTextField();
        r_female = new javax.swing.JRadioButton();
        r_male = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnrecord = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.black, null, null));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("search employee:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, java.awt.Color.black));
        jPanel3.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Attach");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(1040, 380, 79, 30);

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jDesktopPane1);
        jDesktopPane1.setBounds(940, 90, 264, 249);
        jPanel3.add(txt_dept);
        txt_dept.setBounds(640, 190, 230, 30);
        jPanel3.add(txt_job);
        txt_job.setBounds(640, 400, 230, 30);
        jPanel3.add(txt_doh);
        txt_doh.setBounds(640, 290, 230, 30);
        jPanel3.add(txt_salary);
        txt_salary.setBounds(640, 350, 230, 30);
        jPanel3.add(txt_status);
        txt_status.setBounds(640, 450, 230, 30);
        jPanel3.add(txt_apt);
        txt_apt.setBounds(640, 90, 230, 30);
        jPanel3.add(txt_pc);
        txt_pc.setBounds(640, 140, 230, 30);
        jPanel3.add(txt_design);
        txt_design.setBounds(640, 240, 230, 30);
        jPanel3.add(txt_id);
        txt_id.setBounds(180, 90, 220, 30);
        jPanel3.add(txt_firstname);
        txt_firstname.setBounds(180, 140, 220, 30);
        jPanel3.add(txt_dob);
        txt_dob.setBounds(180, 320, 220, 30);
        jPanel3.add(txt_surname);
        txt_surname.setBounds(180, 200, 220, 30);
        jPanel3.add(txt_address);
        txt_address.setBounds(180, 470, 220, 30);
        jPanel3.add(txt_email);
        txt_email.setBounds(180, 370, 220, 30);
        jPanel3.add(txt_tel);
        txt_tel.setBounds(180, 420, 220, 30);
        jPanel3.add(txt_address2);
        txt_address2.setBounds(180, 520, 220, 30);

        r_female.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });
        jPanel3.add(r_female);
        r_female.setBounds(297, 260, 90, 25);

        r_male.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        jPanel3.add(r_male);
        r_male.setBounds(180, 260, 80, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Employee ID:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 90, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("First Name:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 150, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Date of Birth:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 320, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Surname:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 200, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Address2:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 470, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Address1:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 520, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Contact:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 420, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Email:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 370, 90, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Gender:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(30, 250, 80, 35);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Apt./house no:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(510, 90, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Post Code:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(510, 140, 100, 32);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Department:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(510, 190, 100, 35);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Designation:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(510, 240, 95, 35);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("Date Hired:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(510, 290, 100, 35);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Basic Salary:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(510, 350, 100, 38);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Job Title:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(510, 400, 95, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("Status:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(510, 450, 95, 36);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(750, 600, 120, 50);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(610, 600, 120, 50);

        btnrecord.setText("Add Record");
        btnrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecordActionPerformed(evt);
            }
        });
        jPanel3.add(btnrecord);
        btnrecord.setBounds(610, 531, 123, 50);

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(750, 532, 123, 50);

        jLabel19.setFont(new java.awt.Font("Bodoni Bk BT", 2, 12)); // NOI18N
        jLabel19.setText("Employee form");

        jLabel20.setFont(new java.awt.Font("Bodoni Bk BT", 2, 14)); // NOI18N
        jLabel20.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecordActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){
        
        try{
            String sql ="insert into Staff_information"
                    + "(First_name,surname,Dob,Email,"
                    + "Telephone,Address,Department,"
                    + "Image,Salary,Gender,Address2,"
                    + "Post_code,Designation,Status,job_title,Apartment,Date_hired) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            
            pst =conn.prepareStatement(sql);
            pst.setString(1,txt_firstname.getText());
            pst.setString(2,txt_surname.getText());
            pst.setString(3,txt_dob.getText());
            pst.setString(4,txt_email.getText());
            pst.setString(5,txt_tel.getText());
            pst.setString(6,txt_address.getText());
            pst.setString(7,txt_dept.getText());
            pst.setBytes(8, person_image);
            
            pst.setString(9,txt_salary.getText());
            pst.setString(10,gender);
            
            pst.setString(11,txt_address2.getText());
            pst.setString(12,txt_pc.getText());
            pst.setString(13,txt_design.getText());
            pst.setString(14,txt_status.getText());
            pst.setString(15,txt_job.getText());
            pst.setString(16,txt_apt.getText());
            pst.setString(17,txt_doh.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data is saved successfully");
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
        
        try{
            
            String sq ="select * from Staff_information where (id) NOT IN (select id from Users)";
            pst =conn.prepareStatement(sq);
            rs =pst.executeQuery();
            
            
            while(rs.next()){
                String add1 =rs.getString("id");
                String add2 =rs.getString("First_name");
                String add3 =rs.getString("Dob");
                String result =add3.replace("/", "");
                String add4 =rs.getString("Department");
                
                String sql ="insert into Users(division,username,password,emp_id) values('"+add4+"','"+add2+"','"+result+"','"+add1+"')";
                
                pst =conn.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "User account has been created successfully: " +"Username:  "+add2+"password:   "+ result);
                
                
                
            } 
            
            
            
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
       
        
        finally {
                try{
                rs.close();
                pst.close();
                
                }
                catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
                }
                
                
                }
        
        }
        
    }//GEN-LAST:event_btnrecordActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        // TODO add your handling code here:
        gender = "Male";
        r_male.setSelected(true);
        r_female.setSelected(false);

    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        // TODO add your handling code here:
         gender = "Female";
        r_female.setSelected(true);
        r_male.setSelected(false);
    }//GEN-LAST:event_r_femaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        
        filename  = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);
        
        try{
            File image = new File(filename);
            FileInputStream fix = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf = new byte[1024];
            
            for(int number;(number = fix.read(buf))!= -1;){
                
                bos.write(buf,0, number);
                
            }
            person_image = bos.toByteArray();
            
            
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        try{
    String sql="select*from Staff_information where id=?";
pst=conn.prepareStatement(sql);
pst.setString(1,txt_search.getText());
rs=pst.executeQuery();


    String add1=rs.getString("id");
txt_id.setText(add1); 

    String add2=rs.getString("First_name");
txt_firstname.setText(add2); 

        String add3=rs.getString("surname");
txt_surname.setText(add3); 

String add4=rs.getString("Dob");
txt_dob.setText(add4);

String add5=rs.getString("Email");
txt_email.setText(add5); 

String add6=rs.getString("Telephone");
txt_tel.setText(add6); 

String add7=rs.getString("Address");
txt_address.setText(add7); 

String add8=rs.getString("Department");
txt_dept.setText(add8); 

String add10=rs.getString("Salary");
txt_salary.setText(add10); 

String add11=rs.getString("Address2");
txt_address2.setText(add11); 

String add12=rs.getString("Apartment");
txt_apt.setText(add12); 

String add13=rs.getString("Post_code");
txt_pc.setText(add13); 

String add14=rs.getString("Status");
txt_status.setText(add14); 

String add15=rs.getString("Date_hired");
txt_doh.setText(add15); 

String add16=rs.getString("Job_title");
txt_job.setText(add16); 


    String add17=rs.getString("Designation");
txt_design.setText(add17); 




  byte[]image=rs.getBytes("image");
ImageIcon imageIcon = new
 ImageIcon(new ImageIcon(image).getImage().getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_SMOOTH));
img.setIcon(imageIcon);

}catch(Exception e){

}
finally{
 try{
     rs.close();
pst.close();

}catch(Exception e){

}}
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="delete from Staff_information where id=? ";
            pst=conn.prepareStatement(sql);
             pst.setString(1,txt_id.getText());
             pst.execute();
             
             JOptionPane.showMessageDialog(null, "Record Deleted");
            
     
            
           }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
              rs.close();
              pst.close();; 
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txt_id.setText("");
        txt_firstname.setText("");
        txt_surname.setText("");
        txt_tel.setText("");
        txt_dob.setText("");
        txt_email.setText("");
        txt_address.setText("");
        txt_dept.setText("");
        txt_status.setText("");
        txt_salary.setText("");
        txt_address2.setText("");
        txt_pc.setText("");
        txt_job.setText("");
        txt_apt.setText("");
        txt_doh.setText("");
        txt_design.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            
            String val= txt_firstname.getText();
            String val2= txt_surname.getText();
            String val3= txt_dob.getText();
           // String val4= txt_id.getText();
            String val5= txt_email.getText();
            String val6= txt_tel.getText();
            String val7= txt_address.getText();
            String val8= txt_salary.getText();
            String val9= txt_address2.getText();
            String val10= txt_apt.getText();
            String val11= txt_status.getText();
            String val12= txt_dept.getText();
            String val13= txt_design.getText();
            String val14= txt_doh.getText();
            String val15= txt_job.getText();
            String val16= txt_pc.getText();
            
            
            String sql = "update Staff_information set first_name = '"+val+"',surname= '"+val2+"',Dob= '"+val3+"',Email = '"+val5+"',   "
                    + "Telephone = '"+val6+"',Address = '"+val7+"',Salary = '"+val8+"',Address2 = '"+val9+"',Apartment = '"+val10+"',"
                    + "Status = '"+val11+"',Department = '"+val12+"',Designation = '"+val13+"',Date_hired = '"+val14+"',job_title = '"+val15+"',"
                    + "Post_code = '"+val16+"'  ";
            
            pst = conn.prepareStatement(sql);
            pst.execute();
             JOptionPane.showMessageDialog(null, "Record Update");
            

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        finally{
            try{
                rs.close();
                pst.close();;
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrecord;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_address2;
    private javax.swing.JTextField txt_apt;
    private javax.swing.JTextField txt_dept;
    private javax.swing.JTextField txt_design;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doh;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_job;
    private javax.swing.JTextField txt_pc;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;
    String filename = null;
    byte [] person_image = null;
    
    
    
private String gender;
}
