/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Emmanuel Obiajuru
 */
public class login extends javax.swing.JFrame {
        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        mytime mt = new mytime();
         Timer tim = new Timer(1000, mt);
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        
         conn = db.java_db();
         currentDate();
          tim.start();
    }
        private void currentDate(){
             Calendar cal = new GregorianCalendar();
        int month  = cal.get(Calendar.MONTH);
        int year  = cal.get(Calendar.YEAR);
        int day  = cal.get(Calendar.DAY_OF_MONTH);
        
        lbl_date.setText((month +1)+"/"+day+"/"+year);
        }
        
       /* int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        lbl_time.setText(hour+":"+(minute)+":"+second);*/
       class mytime implements ActionListener {
         public void actionPerformed (ActionEvent e){
             Date newdate = new Date();
             String newmydate = String.valueOf(newdate);
             String acc = "";
             for (int i = 11; i< 20; i++){
                 acc= acc + String.valueOf(newmydate.charAt(i));
             }
              lbl_time.setText(acc);
         }  
       }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        txt_combo = new javax.swing.JComboBox<>();
        txt_password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        lbl_date = new javax.swing.JMenu();
        lbl_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please enter your usename and password:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 320, 260, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 370, 66, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 410, 63, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Division:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 450, 51, 17);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 500, 70, 23);
        jPanel1.add(txt_username);
        txt_username.setBounds(170, 370, 140, 30);

        txt_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Sales", "Networking" }));
        txt_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_comboActionPerformed(evt);
            }
        });
        jPanel1.add(txt_combo);
        txt_combo.setBounds(170, 450, 140, 30);
        jPanel1.add(txt_password);
        txt_password.setBounds(170, 410, 140, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/bk3.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, -10, 800, 560);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        lbl_date.setText("Date");
        jMenuBar1.add(lbl_date);

        lbl_time.setText("Time");
        jMenuBar1.add(lbl_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          
        
        
        String sql = "select id, username, password, division from users where (username =? and password =? and division =? )";
        
        
         try{
            int count = 0;
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_username.getText());
            pst.setString(2, txt_password.getText());
            pst.setString(3, txt_combo.getSelectedItem().toString());
            
            rs = pst.executeQuery();
            
             while(rs.next()){
                  int id =rs.getInt(1);
                  Emp.empId = id;
                  String username = rs.getString("username");
                  String division = rs.getString("division");
                  Emp.empname = username;
                  count = count+1;
                 
                  
                  
              }
            String access = (txt_combo.getSelectedItem().toString());
             
            
              if(access == "Admin") {
                        if (count == 1){
                            JOptionPane.showMessageDialog(null,"Successfull");
                            MainMenu j = new MainMenu();
                            j.setVisible(true);
                            this.dispose();
                       
                       Date currentDate = GregorianCalendar.getInstance().getTime();
                            DateFormat df = DateFormat.getDateInstance();
                            String dateString = df.format(currentDate);
                            Date d = new Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
                            String timeString = sdf.format(d);
                            
                            String value0 = timeString;
                            String values = dateString;
                            
                            
                            int value = Emp.empId;
                            
                            String reg = "insert into Audit (emp_id,date,status) values ('"+value+"','"+value0+" / "+values+"','Logged in' )";
                            pst=conn.prepareStatement(reg);
                            pst.execute();
                            this.dispose();
                            
                                    
                                    
                        
                        }
                           
                            
                        
                        
             
              }else if(access == "Sales"){
                  if (count == 1){
                            JOptionPane.showMessageDialog(null,"Successfull");
                            MainMenu j = new MainMenu();
                            j.setVisible(true);
                            this.dispose();
                            
                            Date currentDate = GregorianCalendar.getInstance().getTime();
                            DateFormat df = DateFormat.getDateInstance();
                            String dateString = df.format(currentDate);
                            Date d = new Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
                            String timeString = sdf.format(d);
                            
                            String value0 = timeString;
                            String values = dateString;
                            
                            
                            int value = Emp.empId;
                            
                            String reg = "insert into Audit (emp_id,date,status) values ('"+value+"','"+value0+" / "+values+"','Logged in' )";
                            pst=conn.prepareStatement(reg);
                            pst.execute();
                            this.dispose();
                  }
              }else if (access == "Networking"){
                  if (count == 1){
                            JOptionPane.showMessageDialog(null,"Successfull");
                            MainMenu j = new MainMenu();
                            j.setVisible(true);
                            this.dispose();
                            
                            Date currentDate = GregorianCalendar.getInstance().getTime();
                            DateFormat df = DateFormat.getDateInstance();
                            String dateString = df.format(currentDate);
                            Date d = new Date();
                            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
                            String timeString = sdf.format(d);
                            
                            String value0 = timeString;
                            String values = dateString;
                            
                            
                            int value = Emp.empId;
                            
                            String reg = "insert into Audit (emp_id,date,status) values ('"+value+"','"+value0+" / "+values+"','Logged in' )";
                            pst=conn.prepareStatement(reg);
                            pst.execute();
                            this.dispose();
                            
                  }
              }
         }
         catch (Exception e){
             JOptionPane.showMessageDialog(null, e);
}
         finally{
             try{
                 rs.close();
                pst.close();
                 
             }catch(SQLException e){
                 JOptionPane.showMessageDialog(null, e);
             }
         }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_comboActionPerformed
        // TODO add your handling code here:
        String access = (String) txt_combo.getSelectedItem();
        JOptionPane.showMessageDialog(null, "You have selected " + access);
    }//GEN-LAST:event_txt_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu lbl_date;
    private javax.swing.JMenu lbl_time;
    private javax.swing.JComboBox<String> txt_combo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
